### ISSUE TITLE
401 When pushing documents to a fresh repo

### ISSUE THREAD

**Issue by radiodario** [prismicio/slice-machine#1041]
### Versions

- slice-machine-ui: @latest
- node: 20.3.1

### Reproduction

type  npx @slicemachine/init@latest`

```
✔ Detected framework Next.js 11-13 and package manager npm
✔ Began core dependencies installation with npm ... (running in background)
✔ Logged in as dario*****@*******.***
✔ Selected repository XXXX
✔ Installed core dependencies with npm
✔ Updated Slice Machine configuration and loaded adapter
❯ Pushing data to Prismic...
   ✔ Pushed all slices
   ✔ Pushed all types
   ✖ Pushing documents...
    → Failed to push documents to repository `XXXX`, 401 Unauthorized
    Cleaning up data push artifacts
Error: Failed to push documents to repository `XXXX`, 401 Unauthorized
    at PrismicRepositoryManager.pushDocuments (/Users/dario/.npm/_npx/b6923b01b288b666/node_modules/@slicemachine/manager/dist/managers/prismicRepository/PrismicRepositoryManager.cjs:178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Task.task (/Users/dario/.npm/_npx/b6923b01b288b666/node_modules/@slicemachine/init/dist/SliceMachineInitProcess.cjs:668:15)
 ```
### Steps to reproduce

type `npx @slicemachine/init@latest`

### What is expected?

Documents are pushed to prismic

### What is actually happening?

a cryptic 401 error appears.

**Comment by comeprismic** [comment]
Hi @radiodario! thanks for sharing the issue. Were you trying to initialize one of the Next starters? Can you tell us which one? 
Thanks for this info, we are investigating the issue this week.

**Comment by mdeclercq** [comment]
Hi,

The issue was fixed and the starters have been updated. I'm closing this issue, let us know in case you encounter the issue again.

Thanks,
