### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module at \node_modules\next-slicezone\index.js:1

### ISSUE THREAD

**Issue by jrhager84** [prismicio/slice-machine#121]
### Version

- Prismic CLI version: 3.8.13

### Reproduction

Added slicezone per documentation.

### What is expected?

Using slicezone after install 

### What is actually happening?

```
C:\Users\jrhag\react-sites\edit-elements\node_modules\next-slicezone\index.js:1
import React from 'react'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.next-slicezone (C:\Users\jrhag\react-sites\edit-elements\.next\server\pages\shop\[category]\[uid].js:152:18)
    at __webpack_require__ (C:\Users\jrhag\react-sites\edit-elements\.next\server\webpack-runtime.js:25:42)
    at Object../pages/shop/[category]/[uid].js (C:\Users\jrhag\react-sites\edit-elements\.next\server\pages\shop\[category]\[uid].js:26:72)
    at __webpack_require__ (C:\Users\jrhag\react-sites\edit-elements\.next\server\webpack-runtime.js:25:42)
    at __webpack_exec__ (C:\Users\jrhag\react-sites\edit-elements\.next\server\pages\shop\[category]\[uid].js:195:52)
    at C:\Users\jrhag\react-sites\edit-elements\.next\server\pages\shop\[category]\[uid].js:196:28
    at Object.<anonymous> (C:\Users\jrhag\react-sites\edit-elements\.next\server\pages\shop\[category]\[uid].js:199:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
wait  - compiling...
error - ./node_modules/next-slicezone/index.js
Module parse failed: Unexpected token (6:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| const PageInfo = ({ title, description }) => (
>   <div
|     style={{
|       height: '80vh',
```

### Any additional information

Everything else from Prismic works fine. I *did* have to consult Prismic because I was migrating to an existing repo, and I had to redo some config files, but everything looks as it should (from my estimate). Please let me know what/where I should be looking for to troubleshoot. Thanks!

One of the pages (that I made as a test) that is causing the error:

```
import { client } from '../../../prismic-configuration'
import Prismic from '@prismicio/client'
import { SliceZone } from 'next-slicezone'
import { useGetStaticProps, useGetStaticPaths} from 'next-slicezone/hooks'
import resolver from '../../../sm-resolver'

const CategoryProduct = ({slices}) => {
  return(
    <div>

    </div>
  )
}

export async function getStaticProps(props) {
  const { params: { uid, category }} = props
  console.log(uid, category)
  const products = await client.query([
    Prismic.Predicates.at('', 'product'),
  ])
  const prods = {
    props: {
      products
    }
  }

  return prods
}

export async function getStaticPaths() {
  const results = {
    paths: [
      {
        params: {
          uid: 'handmade-film-transitions',
          category: 'transitions'
        }
      }
    ], fallback: false
  }
  return results
}
```

**Comment by AdamDiament** [comment]
I have the exact same issue

**Comment by AdamDiament** [comment]
Fixed using next-transpile-modules and next-compose-plugins

**Comment by lihbr** [comment]
@hypervillain can you have a look at this one?

**Comment by hypervillain** [comment]
Hey, which version of the slicezone are you using?

**Comment by jrhager84** [comment]
I'm using the 0.1 0 canary/beta that prismic recommends installing.

**Comment by hypervillain** [comment]
Sorry I wasn't clear, I meant the version of [`next-slicezone`](https://www.npmjs.com/package/next-slicezone) but I think you're using 0.0.15.

I see two related issues in your code: you're importing client-side code but don't use it, which might confuse Next.js with where it should import the bundle (client or server side).

Can you try this?
1. Change your import to `import SliceZone from 'next-slicezone'` and use it in your client-side code
2. Remove getStaticProps and Paths from the imports (if not used server-side, they will be included in the client-side build)

**Comment by kb1995** [comment]
Just wanted to flag that I'm getting this error when I try to run `yarn run storybook`

```
ERROR in ./node_modules/next-slicezone/index.js 6:2
Module parse failed: Unexpected token (6:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| const PageInfo = ({ title, description }) => (
>   <div
|     style={{
|       height: '80vh',
 @ ./components/content/Content.tsx 8:0-39 25:35-44
 @ ./components/content/index.tsx
 @ ./components/common/ContentItems.tsx
 @ ./slices/ContentGrid/index.tsx
 @ ./.slicemachine/assets/slices/ContentGrid/index.stories.js
 @ ./.slicemachine/assets sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.23 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core-common/dist/cjs/templates/index.ejs] 1.98 KiB {HtmlWebpackPlugin_0} [built]
ModuleParseError: Module parse failed: Unexpected token (6:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| const PageInfo = ({ title, description }) => (
>   <div
|     style={{
|       height: '80vh',
    at handleParseError (/Users/kris/Documents/code/freelance/miso3/node_modules/webpack/lib/NormalModule.js:469:19)
    at /Users/kris/Documents/code/freelance/miso3/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/kris/Documents/code/freelance/miso3/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/kris/Documents/code/freelance/miso3/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/kris/Documents/code/freelance/miso3/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/kris/Documents/code/freelance/miso3/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/kris/Documents/code/freelance/miso3/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/kris/Documents/code/freelance/miso3/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/kris/Documents/code/freelance/miso3/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm running the latest versions of all libraries

**Comment by hypervillain** [comment]
Can you try to upgrade next-slicezone? (0.1.2)

**Comment by kb1995** [comment]
@hypervillain Working in 0.1.2 - thanks!
