### ISSUE TITLE
Init package fails to initialize project due to outdated `@sentry/node`

### ISSUE THREAD

**Issue by andresmarpz** [prismicio/slice-machine#1380]
### Versions

- slice-machine-ui: v2.1.0
- node: v20.13.1

### Reproduction

No need.

### Steps to reproduce

Just run `npx @slicemachine/init@latest` and it will throw

### What is expected?

That it runs successfully

### What is actually happening?

Due to `@sentry/node` trying to run, the command crashes. The specific error with that version is described below, but is due to `@sentry/node` depending on a previous version of `undici`.

```
 Slice Machine  → Initializing

ℹ We collect telemetry data to improve user experience.
  Learn more: https://prismic.dev/slice-machine/telemetry

TypeError: request.headers.split is not a function
    at setHeadersOnRequest (/Users/redacted/.npm/_npx/b6923b01b288b666/node_modules/@sentry/node/cjs/integrations/undici/index.js:248:39)
    at _onRequestCreate (/Users/redacted/.npm/_npx/b6923b01b288b666/node_modules/@sentry/node/cjs/integrations/undici/index.js:158:9)
    at Channel.publish (node:diagnostics_channel:143:9)
    at new Request (node:internal/deps/undici/undici:6295:27)
    at [dispatch] (node:internal/deps/undici/undici:9077:25)
    at Intercept (node:internal/deps/undici/undici:8812:20)
    at [Intercepted Dispatch] (node:internal/deps/undici/undici:5673:16)
    at Client.dispatch (node:internal/deps/undici/undici:5689:44)
    at [dispatch] (node:internal/deps/undici/undici:5920:32)
    at [Intercepted Dispatch] (node:internal/deps/undici/undici:5666:33)
```

**Comment by xrutayisire** [comment]
Hi, thank you for the issue, we will provide a fix that allow you to init Slice Machine with the latest versions of Node.

In the meantime, you should be able to init with Node v20.12.x

**Comment by xrutayisire** [comment]
Thank you for the issue and the PR, it's now fixed in the last @slicemachine/init version (2.9.19).
