### ISSUE TITLE
Slicemachine process error when saving model to filesystem

### ISSUE THREAD

**Issue by samuelhorn** [prismicio/slice-machine#248]
### Versions

- slice-machine-ui: 0.1.2
- node: 16.13.0

### Reproduction
Only local for now

<details open>
<summary>Additional Details</summary>
<br>
<b>Storybook related modules</b>
<pre>
...
"@nuxtjs/storybook": "^4.2.0",
"@storybook/addon-actions": "^6.4.4",
"@storybook/vue": "^6.3.12",
...
</pre>
</details>

### Steps to reproduce
1. Install slice machine in new Nuxt project as described [here](https://prismic.io/docs/technologies/setup-a-prismic-project-nuxtjs)
2. Install storybook by running `npm i @nuxtjs/storybook @storybook/addon-actions @storybook/vue`
3. Create a new slice and save the model to filesystem.

### What is expected?
Model to be saved without errors.

### What is actually happening?
Model is saved, but when generating screenshot slicmachine process quits with following error:

```
[slice/save]: Updating slice model

[slice/save]: Generating mocks

[slice/save]: Generating stories

[slice/save]: Generating screenshots previews

[slice-machine] node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at BrowserRunner.start (/Users/essisuomalainen/Desktop/Projekt/projekt-huset/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:80:34)
    at ChromeLauncher.launch (/Users/essisuomalainen/Desktop/Projekt/projekt-huset/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:94:16)
    at async Object.handleStorybookPreview (/Users/essisuomalainen/Desktop/Projekt/projekt-huset/node_modules/slice-machine-ui/build/server/src/api/common/storybook.js:54:21)
    at async Object.generateForVariation (/Users/essisuomalainen/Desktop/Projekt/projekt-huset/node_modules/slice-machine-ui/build/server/src/api/previews.js:35:28)
    at async Object.generateForSlice (/Users/essisuomalainen/Desktop/Projekt/projekt-huset/node_modules/slice-machine-ui/build/server/src/api/previews.js:18:17)
    at async handler (/Users/essisuomalainen/Desktop/Projekt/projekt-huset/node_modules/slice-machine-ui/build/server/src/api/slices/save.js:38:31)
    at async /Users/essisuomalainen/Desktop/Projekt/projekt-huset/node_modules/slice-machine-ui/build/server/src/api/index.js:80:21 {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

**Comment by Jamesford** [comment]
Hi @samuelhorn I was having the same issue, but using Next rather than Nuxt. Are you using an M1 Macbook? I discovered [this thread](https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-787912758) and found manually setting the `PUPPETEER_EXECUTABLE_PATH` resolved the process crashing for me.

Here's my updated `slicemachine` npm script.
```
"slicemachine": "PUPPETEER_EXECUTABLE_PATH=\"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome\" start-slicemachine",
```
