### ISSUE TITLE
Cannot read properties of undefined (reading 'DEFAULT_BASE')

### ISSUE THREAD

**Issue by greatwitenorth** [prismicio/slice-machine#572]
### Versions

- slice-machine-ui: 0.4.2
- node: v16.15.0

### Reproduction

I'm trying to follow the instructions after setting up my repository for Next.js:

```
npx degit prismicio-community/nextjs-starter-prismic-blog roadmap-slice-machine && cd roadmap-slice-machine && npx @slicemachine/init --repository roadmap-slice-machine
```

After running `npx @slicemachine/init --repository roadmap-slice-machine` I get the following error in my command line:

```
➜  roadmap-slice-machine npx @slicemachine/init
/Users/nickv/.nvm/versions/node/v16.15.0/lib/node_modules/@slicemachine/init/build/steps/maybe-existing-repo.js:30
const DEFAULT_BASE = core_1.Utils.CONSTS.DEFAULT_BASE;
                                         ^

TypeError: Cannot read properties of undefined (reading 'DEFAULT_BASE')
    at Object.<anonymous> (/Users/nickv/.nvm/versions/node/v16.15.0/lib/node_modules/@slicemachine/init/build/steps/maybe-existing-repo.js:30:42)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/nickv/.nvm/versions/node/v16.15.0/lib/node_modules/@slicemachine/init/build/steps/index.js:8:29)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

<details open>
<summary>Additional Details</summary>
<br>

**package.json**

```
{
  "name": "nextjs-starter-prismic-blog",
  "version": "0.0.0",
  "private": true,
  "license": "Apache-2.0",
  "author": "Prismic <contact@prismic.io> (https://prismic.io)",
  "scripts": {
    "dev": "concurrently \"npm:next:dev\" \"npm:slicemachine\" --names \"next,slicemachine\" --prefix-colors blue,magenta",
    "next:dev": "next",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "slicemachine": "start-slicemachine",
    "format": "prettier --write .",
    "gen": "prismic-ts-codegen"
  },
  "dependencies": {
    "@prismicio/client": "^6.6.4",
    "@prismicio/helpers": "^2.3.2",
    "@prismicio/next": "^0.1.3",
    "@prismicio/react": "^2.4.4",
    "@prismicio/slice-simulator-react": "^0.2.2",
    "clsx": "^1.2.1",
    "next": "12.2.5",
    "prismic-cli": "^4.2.3",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@prismicio/types": "^0.2.2",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "autoprefixer": "^10.4.8",
    "concurrently": "^7.3.0",
    "eslint": "8.22.0",
    "eslint-config-next": "12.2.5",
    "postcss": "^8.4.16",
    "prettier": "^2.7.1",
    "prettier-plugin-tailwindcss": "^0.1.13",
    "prismic-ts-codegen": "^0.1.2",
    "slice-machine-ui": "^0.4.2",
    "tailwindcss": "^3.1.8"
  }
}
```

</details>

### Steps to reproduce

- Create new respository on Prismic.io and select Next.js
- follow the instructions on screen:
```
npx degit prismicio-community/nextjs-starter-prismic-blog roadmap-slice-machine && cd roadmap-slice-machine && npx @slicemachine/init --repository roadmap-slice-machine
```

### What is expected?

- I expected the command to complete without errors

### What is actually happening?

- The command is encountering errors.

**Comment by Heyrows** [comment]
Hey @greatwitenorth I did the following steps:
- go to [the Prismic dashboard](https://prismic.io/dashboard)
- create a repository and select the Next Blog Starter
- Copied the command from my empty repository
```
 test-init npx degit prismicio-community/nextjs-starter-prismic-blog sefvdrgfsdc && cd sefvdrgfsdc && npx @slicemachine/init --repository sefvdrgfsdc
```
- Ran the command in my terminal and got the following result.
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/41187899/186460871-7f64eea8-97d6-4a7b-a55c-f81f98bdf237.png">

**Are you still having this issue ?**

**Comment by greatwitenorth** [comment]
@Heyrows I did the exact same thing and I get the following:

<img width="1226" alt="Screen Shot 2022-08-26 at 9 06 18 AM" src="https://user-images.githubusercontent.com/547583/186922046-c924e898-a751-4592-bda0-4085eb17fc8f.png">

**Comment by Heyrows** [comment]
hey @greatwitenorth.
It looks like a problem on compatibility between the `@slicemachine/init` and `@slicemachine/core` (a dependency).

Can you verify that one of these package isn't installed locally and try the following command to see if the problem persist. 🙏 
```
npx @slicemachine/init@latest --repository roadmap-slice-machine
```

**Comment by greatwitenorth** [comment]
Thanks @Heyrows! running the following command seems to have fixed the issue:

```
npx @slicemachine/init@latest --repository roadmap-slice-machine
```

**Comment by Heyrows** [comment]
I'm glad to hear it @greatwitenorth 😊.
Did you had any packages installed globally ?

**Comment by greatwitenorth** [comment]
Yes it looks like I had @slicemachine/init installed globally.
