### ISSUE TITLE
Error when trying to edit a slice via Slice Builder UI

### ISSUE THREAD

**Issue by pablogiralt** [prismicio/slice-machine#84]
### Version

- Prismic CLI version (know it by running `prismic --version`): 3.8.8

### Reproduction

1. Run Slice Builder using `prismic sm --develop`

2. Open Slice Builder at http://localhost:9999/ and access my first created slice (via `prismic sm --create-slice`)

3. Add a new field and click on **Save model to filesystem**

### What is expected?

I expect new field to be saved

### What is actually happening?

Feld is not being saved and error appears in terminal:
```
[slice-machine] [update]: generating mocks

[slice-machine] (node:49124) UnhandledPromiseRejectionWarning: TypeError: content.flat is not a function
    at createMockFromConfig (/Users/pablo/jamstack/peanutbutter-site/node_modules/slice-machine-ui/lib/widgets/StructuredText/Mock/index.js:75:18)
    at handleMockConfig (/Users/pablo/jamstack/peanutbutter-site/node_modules/slice-machine-ui/lib/widgets/StructuredText/Mock/index.js:83:10)
    at handleFieldMock (/Users/pablo/jamstack/peanutbutter-site/node_modules/slice-machine-ui/lib/mock/handlers.js:23:12)
    at fields.reduce (/Users/pablo/jamstack/peanutbutter-site/node_modules/slice-machine-ui/lib/mock/handlers.js:41:20)
    at Array.reduce (<anonymous>)
    at /Users/pablo/jamstack/peanutbutter-site/node_modules/slice-machine-ui/lib/mock/handlers.js:36:17
    at model.variations.map.variation (/Users/pablo/jamstack/peanutbutter-site/node_modules/slice-machine-ui/lib/mock/index.js:15:20)
    at Array.map (<anonymous>)
    at default (/Users/pablo/jamstack/peanutbutter-site/node_modules/slice-machine-ui/lib/mock/index.js:12:39)
    at handler (/Users/pablo/jamstack/peanutbutter-site/node_modules/slice-machine-ui/server/api/update.js:77:29)

[slice-machine] (node:49124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:49124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

### Any additional information

If I access my storybook for this slice I see this error:

<img width="1353" alt="Screen Shot 2021-03-08 at 17 11 23" src="https://user-images.githubusercontent.com/9419680/110348008-7b944700-8031-11eb-8be7-111c14a41d72.png">

**Comment by lihbr** [comment]
Hey @pablogiralt, thanks for opening an issue!

Can you share your version of Slice Machine UI please? (inside your `package.json`) Thanks!

(cc @hypervillain)

**Comment by pablogiralt** [comment]
sure @lihbr, I am using 0.0.44

**Comment by pablogiralt** [comment]
ok, so I was using node 10.  I have switched to v12 and now I'm not getting the `content.flat() is not a function` error.

I imagine that js function is not available in node 10

**Comment by lihbr** [comment]
Oh great! Glad you figured it out~

Indeed Slice Machine requires v12 now at least, we'll have some warning enforcing that pretty soon 🙂

**Comment by pablogiralt** [comment]
thanks @lihbr! closing this
