### ISSUE TITLE
slice-machine-ui 0.0.44 error TypeError: content.flat is not a function

### ISSUE THREAD

**Issue by bobsingor** [prismicio/slice-machine#88]
### Version

- Prismic CLI version (know it by running `prismic --version`): 3.8.9

### Reproduction

After updating to slice-machine-ui 0.0.44 we are unable to push a slice to prismic.

We get the following error:

TypeError: content.flat is not a function
[slice-machine] [update]: generating mocks

[slice-machine] (node:74581) UnhandledPromiseRejectionWarning: TypeError: content.flat is not a function
    at createMockFromConfig (/Users/bobsingor/Github/testproject/node_modules/slice-machine-ui/lib/widgets/StructuredText/Mock/index.js:73:18)
    at handleMockConfig (/Users/bobsingor/Github/testproject/node_modules/slice-machine-ui/lib/widgets/StructuredText/Mock/index.js:83:10)
    at handleFieldMock (/Users/bobsingor/Github/testproject/node_modules/slice-machine-ui/lib/mock/handlers.js:14:12)
    at reduce (/Users/bobsingor/Github/testproject/node_modules/slice-machine-ui/lib/mock/handlers.js:29:20)
    at Array.reduce (<anonymous>)
    at handler (/Users/bobsingor/Github/testproject/node_modules/slice-machine-ui/lib/mock/handlers.js:24:17)
    at map (/Users/bobsingor/Github/testproject/node_modules/slice-machine-ui/lib/mock/index.js:18:20)
    at Array.map (<anonymous>)
    at mock (/Users/bobsingor/Github/testproject/node_modules/slice-machine-ui/lib/mock/index.js:15:39)
    at handler (/Users/bobsingor/Github/testproject/node_modules/slice-machine-ui/server/api/update.js:53:31)

**Comment by lihbr** [comment]
Hey Bob, hope you're doing well! Thanks for letting us known, we'll have a look at it!

@arnaudlewis / @hypervillain maybe

**Comment by hypervillain** [comment]
Hey @bobsingor, try upgrading node to v12-14.

@lihbr We'll add a warning on 0.1 that checks node version before launching the actual builder

**Comment by lihbr** [comment]
Awesome @hypervillain, for the warning check: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines might already be helpful :)
